package de.tomcory.heimdall.core.vpn.quic

import de.tomcory.heimdall.core.vpn.integration.support.QuicInitialFixtures
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Test
import java.io.File

/**
 * Keeps the canned QUIC client Initials that `scripts/emulator-traffic.sh` sends in its "quic"
 * group (docs/vpn-mitm-audit.md PKT-50) identical to what [QuicInitialFixtures] produces, and
 * checks that each of them yields the expected ClientHello.
 *
 * Initial keys depend only on the version and the Destination Connection ID, so the datagrams
 * stay valid forever. To regenerate the file after changing the cases, run this test with the
 * environment variable `HEIMDALL_WRITE_QUIC_INITIALS=1`.
 */
class QuicCannedInitialsTest {

    private class Case(val name: String, val sni: String, val alpn: List<String>, val version: Int, val datagrams: Int, val extraLength: Int)

    private val cases = listOf(
        Case("h3", "quic-h3.example", listOf("h3"), QuicInitialKeys.VERSION_1, 1, 0),
        Case("doq", "quic-doq.example", listOf("doq"), QuicInitialKeys.VERSION_1, 1, 0),
        Case("split", "quic-split.example", listOf("h3"), QuicInitialKeys.VERSION_1, 2, 1300),
        Case("v2", "quic-v2.example", listOf("h3"), QuicInitialKeys.VERSION_2, 1, 0)
    )

    // the unit tests run in the module directory
    private val file = File("../../scripts/quic-initials.txt")

    private fun render(): String {
        val lines = mutableListOf(
            "# Canned QUIC client Initial datagrams for the \"quic\" group of scripts/emulator-traffic.sh.",
            "# Generated by core/vpn/src/test/java/de/tomcory/heimdall/core/vpn/quic/QuicCannedInitialsTest.kt;",
            "# do not edit by hand. One case per line: name, SNI, ALPN, then one hex string per datagram."
        )
        for (case in cases) {
            val clientHello = QuicInitialFixtures.clientHello(case.sni, case.alpn, case.extraLength)
            val flight = QuicInitialFixtures.clientInitialDatagrams(
                clientHello,
                version = case.version,
                destinationConnectionId = QuicInitialFixtures.RandomBytes.of(8, case.name.hashCode().toLong()),
                datagrams = case.datagrams,
                shuffle = case.datagrams > 1
            )
            val hex = flight.joinToString(" ") { datagram -> datagram.joinToString("") { "%02x".format(it) } }
            lines.add("${case.name} ${case.sni} ${case.alpn.joinToString(",")} $hex")
        }
        return lines.joinToString("\n", postfix = "\n")
    }

    @Test
    fun `the canned Initials match the fixture and yield their ClientHellos`() {
        val expected = render()
        if (System.getenv("HEIMDALL_WRITE_QUIC_INITIALS") == "1") {
            file.writeText(expected)
        }
        assertTrue("${file.absolutePath} is missing; run with HEIMDALL_WRITE_QUIC_INITIALS=1", file.exists())
        assertEquals("the canned Initials are out of date; run with HEIMDALL_WRITE_QUIC_INITIALS=1", expected, file.readText())

        for (line in expected.lines().filter { it.isNotBlank() && !it.startsWith("#") }) {
            val fields = line.split(" ")
            val inspector = QuicInitialInspector()
            fields.drop(3).forEach { hex ->
                inspector.offer(ByteArray(hex.length / 2) { hex.substring(it * 2, it * 2 + 2).toInt(16).toByte() })
            }
            val result = inspector.result
            assertTrue("${fields[0]}: ${(result as? QuicInitialInspector.Result.GaveUp)?.reason}", result is QuicInitialInspector.Result.Complete)
            result as QuicInitialInspector.Result.Complete
            assertEquals(fields[1], result.clientHello.sni)
            assertEquals(fields[2].split(","), result.clientHello.alpn)
        }
    }
}
