package de.tomcory.heimdall.service

import de.tomcory.heimdall.core.vpn.mitm.Authority
import de.tomcory.heimdall.core.vpn.mitm.KeyStoreHelper
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import java.io.File
import java.math.BigInteger
import java.security.KeyStore
import java.security.cert.X509Certificate

/**
 * Generates (or loads) Heimdall's MitM root CA and exports it to [exportDir], for callers outside
 * the UI such as [CaCertificateCommandReceiver].
 *
 * @param keyStoreDir the directory holding the CA key store (`filesDir/keystore`, shared with
 * [HeimdallVpnService] and the settings exporters)
 * @param exportDir the directory the CA certificate is exported to
 * @param isVpnActive whether the VPN is currently running; a forced regeneration is refused while
 * it is, since the running MitM components keep using the CA they already loaded
 */
class CaCertificateGenerator(
    private val keyStoreDir: File,
    private val exportDir: File,
    private val isVpnActive: suspend () -> Boolean
) {

    sealed class Outcome {
        data class Generated(val export: KeyStoreHelper.CaExport) : Outcome()
        data class Reused(val export: KeyStoreHelper.CaExport) : Outcome()
        data object RefusedVpnActive : Outcome()
        data class Failed(val error: Throwable) : Outcome()
    }

    /**
     * Loads the existing CA if it is still valid, or generates a new one otherwise, and exports
     * it. With [force], any existing CA is deleted first so that a new one is always generated.
     */
    suspend fun generate(force: Boolean): Outcome = withContext(Dispatchers.IO) {
        try {
            if (force && isVpnActive()) {
                return@withContext Outcome.RefusedVpnActive
            }

            val authority = Authority.getDefaultInstance(keyStoreDir)
            if (force) {
                KeyStoreHelper.deleteKeyStore(authority)
            }

            // compare serials rather than checking file existence, so that an expired or
            // unreadable CA regenerated by initialiseOrLoadKeyStore also counts as generated
            val previousSerial = previousSerial(authority)
            val keyStore = KeyStoreHelper.initialiseOrLoadKeyStore(authority)
            val serial = (keyStore.getCertificate(authority.alias) as X509Certificate).serialNumber

            val export = KeyStoreHelper.exportCaFiles(authority, keyStore, exportDir)
            if (serial == previousSerial) Outcome.Reused(export) else Outcome.Generated(export)
        } catch (e: Exception) {
            Outcome.Failed(e)
        }
    }

    /**
     * Returns the serial number of the CA certificate currently stored for [authority], or `null`
     * if there is no key store or it can't be read.
     */
    private fun previousSerial(authority: Authority): BigInteger? {
        val keyStoreFile = File(authority.keyStoreDir, "${authority.alias}.p12")
        if (!keyStoreFile.exists()) {
            return null
        }
        return try {
            val keyStore = KeyStore.getInstance("PKCS12")
            keyStoreFile.inputStream().use { keyStore.load(it, authority.password) }
            (keyStore.getCertificate(authority.alias) as? X509Certificate)?.serialNumber
        } catch (e: Exception) {
            null
        }
    }
}
